# Generated by Django 5.2.4 on 2025-07-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='preview_video_duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='preview_video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly', null=True, upload_to='bundle_previews/'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='preview_video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='bundle_preview_thumbnails/'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='preview_video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or other video platform URL'),
        ),
    ]
