# Generated by Django 5.2.4 on 2025-07-15 19:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BECEPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('paper1', 'Paper 1 - Objective'), ('paper2', 'Paper 2 - Essay')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('total_marks', models.IntegerField(default=100)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BECESubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mathematics', 'Mathematics'), ('english_language', 'English Language'), ('integrated_science', 'Integrated Science'), ('social_studies', 'Social Studies'), ('religious_moral_education', 'Religious and Moral Education'), ('ghanaian_language', 'Ghanaian Language'), ('french', 'French'), ('ict', 'Information and Communication Technology'), ('creative_arts', 'Creative Arts'), ('career_technology', 'Career Technology')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_core', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BECEYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='BECEPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('time_taken_minutes', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='bece.becepaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bece_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BECEQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bece_questions/')),
                ('marks', models.IntegerField(default=1)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bece.becepaper')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('paper', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='BECEAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='bece.becequestion')),
            ],
            options={
                'unique_together': {('question', 'option_letter')},
            },
        ),
        migrations.AddField(
            model_name='becepaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='bece.becesubject'),
        ),
        migrations.CreateModel(
            name='BECEUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_earned', models.IntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='bece.becepracticeattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bece.becequestion')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bece.beceanswer')),
            ],
        ),
        migrations.AddField(
            model_name='becepaper',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='bece.beceyear'),
        ),
        migrations.CreateModel(
            name='BECEStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bece_stats', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='bece.becesubject')),
            ],
            options={
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='becepaper',
            unique_together={('year', 'subject', 'paper_type')},
        ),
    ]
