# Generated by Django 5.2.4 on 2025-07-22 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bece', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becequestion',
            name='essay_instructions',
            field=models.TextField(blank=True, help_text='Instructions for essay questions'),
        ),
        migrations.AddField(
            model_name='becequestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer'),
        ),
        migrations.AddField(
            model_name='becequestion',
            name='learning_objective',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='becequestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('essay', 'Essay'), ('short_answer', 'Short Answer'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='becequestion',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, help_text='Time limit for this question', null=True),
        ),
        migrations.AddField(
            model_name='becequestion',
            name='word_limit',
            field=models.IntegerField(blank=True, help_text='Word limit for essay questions', null=True),
        ),
        migrations.AddField(
            model_name='beceuseranswer',
            name='answered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='beceuseranswer',
            name='teacher_feedback',
            field=models.TextField(blank=True, help_text='Teacher feedback for essay questions'),
        ),
        migrations.AddField(
            model_name='beceuseranswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='Text answer for essay/short answer questions'),
        ),
        migrations.AddField(
            model_name='beceuseranswer',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Time spent on this question'),
        ),
        migrations.AlterUniqueTogether(
            name='beceuseranswer',
            unique_together={('attempt', 'question')},
        ),
    ]
