# Generated by Django 5.2.4 on 2025-07-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_preview_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives/outcomes for this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Prerequisites and prior knowledge required for this course'),
        ),
    ]
