# Generated by Django 5.2.4 on 2025-07-17 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_learning_objectives_course_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField()),
                ('qualification', models.CharField(max_length=300)),
                ('experience_years', models.IntegerField(default=0)),
                ('specialization', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='List of achievements')),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('display_order', models.IntegerField(default=0, help_text='Order on homepage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='courses.subject')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
