# Generated by Django 5.2.4 on 2025-07-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(default=20),
        ),
    ]
