# Generated by Django 5.2.4 on 2025-07-21 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_quiz_time_limit_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or other video platform URL')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file directly', null=True, upload_to='episode_videos/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='episode_thumbnails/')),
                ('is_free', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='EpisodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
